input:
  background_images: /path/to/background/images
  text_file_path: /path/to/text/file
  groundtruth_path: /path/to/groundtruth
output:
  samples_out_dir: /path/to/output
  num_samples_to_save_as_files: 500
rendering:
  special_char:
    spec_char_per_word: {0: 0.0, 1: 0.7, 2: 0.2, 3: 0.1 }
    color_differentiation_th: 30.0
  augmentation:
    augment_image: true
    augmentation_index: 217
    augmentation_probability: 1.0
  background_probabilitiy:
    gaussian_noise: 0.25
    image: 0.3
    plain: 0.45
  character_spacing:
    max: 2
    min: 7
  font_color_standatd: RANDOM
  font_size:
    1:
      max: 26
      min: 16
      prob: 0.25
    2:
      max: 48
      min: 20
      prob: 0.75
  render_only_background: false
rnd_state: 42
