input:
  image_folder_path: 'C:\Users\pc\Desktop\Synthetic-images-generation-using-Blender\image_inputs'
  groundtruth_folder_path: 'C:\Users\pc\Desktop\Synthetic-images-generation-using-Blender\json_inputs'
  
output:
  out_dir: 'C:\Users\pc\Desktop\Synthetic-images-generation-using-Blender\outputs'
  num_samples_per_image: 10
 
shape:
  flat:
    probability: 1
  bended_up: 
    level: high
    probability: 0
    side: Z
  bended_down:
    level: high
    probability: 0
    side: Z
  wrinkled: 
    level: high
    probability: 0
  folded: 
    level: high
    probability: 0
    side: X
  mixed:
    bend_mode: up
    bend_level: medium
    bend_side: Z
    wrinkle_level: medium
    probability: 0

render_resolution_1: 1920
render_resolution_2: 1080

light_colors: False

object_shadow : True

draw_labels : False

render_engine : BLENDER_EEVEE

render_samples : 0 

camera_random_mode : False

rotation_step: 20

